app-template:
  name: '{"zh-cn": "fg-FFmpeg", "en-us": "fg-FFmpeg"}'
  description: '{"zh-cn": "FFmpeg","en-us": "FFmpeg"}'
  path: fg-ffmpeg
  runtime: http
  category: '{"zh-cn": "音视频处理", "en-us": "Audio and video processing"}'
  image: fg-ffmpeg.png
  type: "Media Processing"
  functions:
    ffmpeg-audio-convert:
    ffmpeg-get-duration:
    ffmpeg-get-meta:
    ffmpeg-get-sprites:
    ffmpeg-video-gif:
    ffmpeg-video-watermark: