app-template:
  name: '{"zh-cn": "fg-FFmpeg", "en-us": "fg-FFmpeg"}'
  description: '{"zh-cn": "FFmpeg","en-us": "FFmpeg"}'
  path: fg-ffmpeg
  version: 20240403
  runtime: http
  category: '{"zh-cn": "音视频处理", "en-us": "Audio and video processing"}'
  image: fg-ffmpeg.png
  type: "Media Processing"
  functions:
    ffmpeg-audio-convert:
      config: "{\"enable_auth_in_header\":true}"
    ffmpeg-get-duration:
      config: "{\"enable_auth_in_header\":true}"
    ffmpeg-get-meta:
      config: "{\"enable_auth_in_header\":true}"
    ffmpeg-get-sprites:
      config: "{\"enable_auth_in_header\":true}"
    ffmpeg-video-gif:
      config: "{\"enable_auth_in_header\":true}"
    ffmpeg-video-watermark:
      config: "{\"enable_auth_in_header\":true}"